######################## default configuration ####################
baseURL = "https://examplesite.com"
title = "Anish | Portfolio Website"
theme = "somrat"
# post pagination
paginate = "7"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # disable language from here
# google analutics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


#################### default parameters ################################
[params]
favicon = "images/icons/icon2.png"
logo_light = "images/logo-light.png"
logo_dark = "images/logo-light.png"
logo_width = "150px"
# Meta data
description = "Portfolio Website"
author = "Anish Dobariyapatel"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/channel/UCiUCVyqS-3iFsNuT0vCBYeg/videos"

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/siranishkd"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/anishkishor/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# english navigation ##################

# main menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About me"
pre = "#"
url = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Tools"
pre = "#"
url = "tools"
weight = 3

[[Languages.en.menu.main]]
name = "Portfolio"
pre = "#"
url = "portfolio"
weight = 4

[[Languages.en.menu.main]]
name = "Projects"
url = "projects"
weight = 5

[[Languages.en.menu.main]]
name = "Testimonials"
pre = "#"
url = "testimonial"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7


